### ISSUE TITLE
Clarify documentation about buckets

### ISSUE THREAD

**Issue by leibovic** [mozilla-services/switchboard-experiments#16]
@milescrabill @liuche Is the bucket range inclusive or exclusive? For example, if we have two experiments, A and B, where A is enabled for buckets 0-33 and B is enabled for buckets 33-66, what does a user with a UUID in bucket 33 see? Do they see both experiments enabled?

We should clarify this in the README.

**Comment by milescrabill** [comment]
To clarify, [low, high) is correct. There is no check for out of bounds buckets, so "disabled" experiments can be either out of bounds or have a low == high. There are 100 buckets, and because the high is a non-inclusive upper bound experiments should use 100 as the high value.

https://github.com/mozilla-services/switchboard-experiments/pull/26 clarifies this.
